### ISSUE TITLE
feature request and help

### ISSUE THREAD

**Issue by bazir123** [minhhungit/github-action-rss-crawler#2]
hello
and instructions to run it on my own would be help full
the feature requests is filter rss (if not include word i want delete them)
second post rss with no media to telegram private group.

thanks

**Comment by minhhungit** [comment]
code which is used to github Action run is also committed, you can check it here https://github.com/minhhungit/github-action-rss-crawler/blob/master/.github/workflows/crawl-rss.yml

So just need to create a workflow and it will work for you 
![image](https://user-images.githubusercontent.com/2279508/193412440-9a3b215f-d2e6-4084-8b9a-7cf05147de66.png)

---

About feature request, this repo is just demo how to make use of github action to execute code without paying (but still bellow limitation of github ) and just for fun. So I'm quite lazy to add more features because I don't use it for working. You can fork and modify c# code inside this repository.

Btw, for more serious work, I deployed a rss applicaiton on my bare metal server to crawl rss app and a web app to read rss record and use them to read news about new technology.
